/**
 * Tests for M18: Workflow-generated PR body policy compliance.
 *
 * Proves:
 * 1. Milestones render as "Done:" / "Pending:" plain bullets, not checkboxes
 * 2. No emoji appears anywhere in the output
 * 3. No attribution footer appears
 * 4. Mixed done/pending milestones are correctly distinguished
 * 5. No plan text falls back to "_No plan available_"
 * 6. Workflow metadata (title, task, cycles, model info) still appears
 */
import { describe, it, expect } from 'vitest';
import { _buildPrBody } from '../server/orchestrator/WorkflowManager.js';
import type { Workflow } from '../shared/types.js';

function makeWorkflow(overrides: Partial<Workflow> = {}): Workflow {
  return {
    id: 'wf-test',
    title: 'Test Workflow',
    task: 'Do something useful',
    work_dir: '/tmp/test',
    implementer_model: 'claude-sonnet-4-6',
    reviewer_model: 'codex',
    max_cycles: 5,
    current_cycle: 3,
    current_phase: 'implement',
    status: 'running',
    milestones_total: 0,
    milestones_done: 0,
    project_id: null,
    max_turns_assess: 20,
    max_turns_review: 15,
    max_turns_implement: 50,
    stop_mode_assess: 'turns',
    stop_value_assess: null,
    stop_mode_review: 'turns',
    stop_value_review: null,
    stop_mode_implement: 'turns',
    stop_value_implement: null,
    template_id: null,
    use_worktree: 1,
    worktree_path: '/tmp/wt',
    worktree_branch: 'workflow/test',
    pr_url: null,
    created_at: Date.now(),
    updated_at: Date.now(),
    ...overrides,
  };
}

const PLAN_MIXED = `# Plan

## Milestones

- [x] **M1: First milestone** — already done
- [ ] **M2: Second milestone** — still pending
- [x] **M3: Third milestone** — also done
- [ ] **M4: Fourth milestone** — not yet
`;

const PLAN_ALL_DONE = `# Plan

## Milestones

- [x] **M1: First** — done
- [x] **M2: Second** — done
`;

const PLAN_ALL_PENDING = `# Plan

## Milestones

- [ ] **M1: First** — pending
- [ ] **M2: Second** — pending
`;

describe('_buildPrBody', () => {
  it('renders mixed done/pending milestones as plain bullets', () => {
    const body = _buildPrBody(makeWorkflow(), PLAN_MIXED);
    expect(body).toContain('- Done: **M1: First milestone** — already done');
    expect(body).toContain('- Pending: **M2: Second milestone** — still pending');
    expect(body).toContain('- Done: **M3: Third milestone** — also done');
    expect(body).toContain('- Pending: **M4: Fourth milestone** — not yet');
  });

  it('does not contain any markdown checkboxes', () => {
    const body = _buildPrBody(makeWorkflow(), PLAN_MIXED);
    expect(body).not.toMatch(/\[[ xX]\]/);
  });

  it('does not contain any emoji', () => {
    const body = _buildPrBody(makeWorkflow(), PLAN_MIXED);
    // Check for common emoji patterns (emoji are multi-byte chars above U+1F000 or specific ranges)
    expect(body).not.toMatch(/[\u{1F000}-\u{1FFFF}]/u);
    expect(body).not.toMatch(/[\u{2600}-\u{27BF}]/u);
  });

  it('does not contain attribution footer', () => {
    const body = _buildPrBody(makeWorkflow(), PLAN_MIXED);
    expect(body).not.toContain('Generated by');
    expect(body).not.toContain('autonomous agent run');
  });

  it('includes workflow metadata', () => {
    const wf = makeWorkflow({ title: 'My PR', task: 'Fix all the bugs', current_cycle: 3, max_cycles: 5 });
    const body = _buildPrBody(wf, PLAN_MIXED);
    expect(body).toContain('## My PR');
    expect(body).toContain('**Task:** Fix all the bugs');
    expect(body).toContain('**Cycles:** 3/5');
    expect(body).toContain('**Milestones:** 2/4 complete');
  });

  it('shows all-done milestones correctly', () => {
    const body = _buildPrBody(makeWorkflow(), PLAN_ALL_DONE);
    expect(body).toContain('- Done: **M1: First** — done');
    expect(body).toContain('- Done: **M2: Second** — done');
    expect(body).not.toContain('Pending:');
  });

  it('shows all-pending milestones correctly', () => {
    const body = _buildPrBody(makeWorkflow(), PLAN_ALL_PENDING);
    expect(body).toContain('- Pending: **M1: First** — pending');
    expect(body).toContain('- Pending: **M2: Second** — pending');
    expect(body).not.toContain('Done:');
  });

  it('falls back to placeholder when plan text is null', () => {
    const body = _buildPrBody(makeWorkflow(), null);
    expect(body).toContain('_No plan available_');
    expect(body).toContain('**Milestones:** 0/0 complete');
  });

  it('falls back to placeholder when plan text has no milestones', () => {
    const body = _buildPrBody(makeWorkflow(), '# Plan\n\nSome text but no checkboxes');
    expect(body).toContain('_No plan available_');
  });

  it('does not include model names in the body', () => {
    const body = _buildPrBody(makeWorkflow(), PLAN_MIXED);
    expect(body).not.toContain('Implementer:');
    expect(body).not.toContain('Reviewer:');
  });
});
