import { Router } from 'express';
import jobsRouter from './jobs.js';
import agentsRouter from './agents.js';
import repliesRouter from './replies.js';
import locksRouter from './locks.js';
import templatesRouter from './templates.js';
import projectsRouter from './projects.js';
import usageRouter from './usage.js';
import searchRouter from './search.js';
import batchTemplatesRouter from './batchTemplates.js';
import settingsRouter from './settings.js';
import debatesRouter from './debates.js';
import workflowsRouter from './workflows.js';
import worktreesRouter from './worktrees.js';
import statsRouter from './stats.js';
import knowledgeBaseRouter from './knowledgeBase.js';
import eyeRouter from './eye.js';
import localConfigRouter from './localConfig.js';
import modelsRouter from './models.js';
import healthRouter from './health.js';
import eventsRouter from './events.js';

const router = Router();

router.use('/health', healthRouter);
router.use('/events', eventsRouter);
router.use('/jobs', jobsRouter);
router.use('/agents', agentsRouter);
router.use('/replies', repliesRouter);
router.use('/locks', locksRouter);
router.use('/templates', templatesRouter);
router.use('/projects', projectsRouter);
router.use('/usage', usageRouter);
router.use('/search', searchRouter);
router.use('/batch-templates', batchTemplatesRouter);
router.use('/settings', settingsRouter);
router.use('/debates', debatesRouter);
router.use('/workflows', workflowsRouter);
router.use('/worktrees', worktreesRouter);
router.use('/stats', statsRouter);
router.use('/knowledge-base', knowledgeBaseRouter);
router.use('/eye', eyeRouter);
router.use('/local-config', localConfigRouter);
router.use('/models', modelsRouter);

export default router;
